### ISSUE TITLE
Feature: ViewHolders with kotlin-android-extension's LayoutContainer as dedicated dependecy

### ISSUE THREAD

**Issue by TemMax** [revolut-mobile/RecyclerKit#7]
For example — I doesn't use kotlin-android-extensions in my project and it in RecyclerKit is useless for me.
A good approach — divide features per modules. For example: module with kotlin-android-extensions, module with ViewBinding and etc.

**Comment by yatsinar** [comment]
That's a good suggestion, we'll definitely do that.
If you'd be willing to file your own PR for that I'd only suggest naming: **kextensions** for the module, to be in line with **rxdiffadapter**. And **ContainerRecyclerViewDelegate: BaseRecyclerViewDelegate** for the class with **LayoutContainer** support.

**Comment by TemMax** [comment]
@yatsinar PR is ready: #8 
Need your review

**Comment by yatsinar** [comment]
Dedicated dependency is now available in 
**recyclerkit:delegates:1.0.9** and **recyclerkit:kextensions:1.0.6**
